version: '3.8'

services:
  springboot-app:
    container_name: lowTechGmbH
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ccsummer24
      MYSQL_ROOT_PASSWORD: root