version: '3.8'

services:
   middleware:
     container_name: middleware
     image: middleware
     restart: always
     build:
       context: ./middleware/cc_summer
     ports:
       - 8080:8080
     environment:
       MYSQL_HOST: mysqldb
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_PORT: 3306

   frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./webshop-v3
    ports:
      - 4200:80
    depends_on:
       - middleware

   mysqldb:
     container_name: mysqldb
     image: mysql
     ports:
       - 3306:3306
     environment:
       MYSQL_DATABASE: ccsummer24
       MYSQL_ROOT_PASSWORD: root